<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="Module.RegionalSetup.TC009_CityMasterUploadData" tests="4" failures="1" timestamp="16 Nov 2017 05:49:36 GMT" time="69.271" errors="0">
  <testcase name="Data_Upload" time="10.063" classname="Module.RegionalSetup.TC009_CityMasterUploadData">
    <failure type="java.lang.AssertionError" message="Record Not saved successfully OR Page Crashed : Alert Box Not Present">
      <![CDATA[java.lang.AssertionError: Record Not saved successfully OR Page Crashed : Alert Box Not Present
	at org.testng.Assert.fail(Assert.java:94)
	at pom.ObjectPages.uiActions.CityMaster.Test_AddNewDataUpload(CityMaster.java:102)
	at Module.RegionalSetup.TC009_CityMasterUploadData.Data_Upload(TC009_CityMasterUploadData.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Data_Upload -->
  <testcase name="Login" time="3.490" classname="Module.RegionalSetup.TC009_CityMasterUploadData"/>
  <testcase name="Target_Page" time="47.513" classname="Module.RegionalSetup.TC009_CityMasterUploadData"/>
  <testcase name="AddNew_Button" time="8.205" classname="Module.RegionalSetup.TC009_CityMasterUploadData"/>
</testsuite> <!-- Module.RegionalSetup.TC009_CityMasterUploadData -->
